name: Feature branch checks

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  setup:
    name: Setup code and environment needed for building, linting and tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v2
      - name: Cache Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache module node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Cache Example application node modules
        uses: actions/cache@v3
        id: cache-app-node-modules
        with:
          path: ./Example/node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Install node modules if cache not present
        run: yarn install --immutable
        if: steps.cache-module-node-modules.outputs.cache-hit != 'true'
      - name: Install application node modules if cache not present
        run: yarn install --immutable
        if: steps.cache-example-application-node-modules.outputs.cache-hit != 'true'

  lint:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Restore node modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Lint
        run: yarn lint

  test:
    runs-on: macos-latest
    needs: setup
    timeout-minutes: 20
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Restore node modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Run tests
        run: yarn test

  build-android:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Restore node modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Restore application node modules from cache
        uses: actions/cache@v3
        with:
          path: ./Example/node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Build example application
        run: |
          cd ./Example
          ls
          cd ./android
          ./gradlew assembleDebug
